"""add_raw_to_tariff

Revision ID: 0ebe7dd7eb91
Revises: 6e6bb1a16e1b
Create Date: 2026-05-29 16:22:09.801511

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ebe7dd7eb91'
down_revision: Union[str, None] = '6e6bb1a16e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff', sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariff', 'raw')
    # ### end Alembic commands ###
