"""add nwb road segment

Revision ID: 6fb1dfebfe79
Revises: b4c5d6e7f8a9
Create Date: 2026-07-10 12:33:14.876218

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fb1dfebfe79'
down_revision: Union[str, None] = 'b4c5d6e7f8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nwb_road_segment',
    sa.Column('wvk_id', sa.BigInteger(), nullable=False),
    sa.Column('begin_junction_id', sa.BigInteger(), nullable=True),
    sa.Column('end_junction_id', sa.BigInteger(), nullable=True),
    sa.Column('road_number', sa.String(), nullable=True),
    sa.Column('street_name', sa.String(), nullable=True),
    sa.Column('road_manager_type', sa.String(), nullable=True),
    sa.Column('road_manager_name', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('administrative_direction', sa.String(), nullable=True),
    sa.Column('carriageway_position', sa.String(), nullable=True),
    sa.Column('position_to_orientation_line', sa.String(), nullable=True),
    sa.Column('carriageway_type', sa.String(), nullable=True),
    sa.Column('frc', sa.Integer(), nullable=True),
    sa.Column('form_of_way', sa.Integer(), nullable=True),
    sa.Column('openlr', sa.String(), nullable=True),
    sa.Column('begin_km', sa.Numeric(), nullable=True),
    sa.Column('end_km', sa.Numeric(), nullable=True),
    sa.Column('length_m', sa.Numeric(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('road_class', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('wvk_id')
    )
    op.create_index('ix_nwb_road_segment_geom', 'nwb_road_segment', ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nwb_road_segment_geom', table_name='nwb_road_segment', postgresql_using='gist')
    op.drop_table('nwb_road_segment')
    # ### end Alembic commands ###
