"""initial schema

Revision ID: d606f4f43b64
Revises: 
Create Date: 2026-05-29 15:21:54.698690

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd606f4f43b64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_point',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cpo_id', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('operator_name', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('open', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_charge_point_geom', 'charge_point', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('drip',
    sa.Column('controller_id', sa.String(), nullable=False),
    sa.Column('vms_index', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vms_type', sa.String(), nullable=True),
    sa.Column('physical_support', sa.String(), nullable=True),
    sa.Column('bearing', sa.Integer(), nullable=True),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('controller_id', 'vms_index')
    )
    op.create_index('ix_drip_geom', 'drip', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('emission_zone',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('zone_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('authority', sa.String(), nullable=True),
    sa.Column('info_url', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emission_zone_geom', 'emission_zone', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('feed_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feed', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('etag', sa.String(), nullable=True),
    sa.Column('last_modified', sa.String(), nullable=True),
    sa.Column('rows_upserted', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement_site',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('equipment_type', sa.String(), nullable=True),
    sa.Column('num_lanes', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('record_version_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_measurement_site_geom', 'measurement_site', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('meetlocatie_punt',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meetlocatie_punt_geom', 'meetlocatie_punt', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('meetlocatie_vak',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meetlocatie_vak_geom', 'meetlocatie_vak', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('msi_sign',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('road', sa.String(), nullable=True),
    sa.Column('carriageway', sa.String(), nullable=True),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.Column('km', sa.Numeric(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('ix_msi_sign_geom', 'msi_sign', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('situation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('record_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('probability', sa.String(), nullable=True),
    sa.Column('safety_related', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('speed_limit_kmh', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_situation_category', 'situation', ['category'], unique=False)
    op.create_index('ix_situation_geom', 'situation', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('tariff',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('party_id', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('elements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffic_sign',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rvv_code', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('placement', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('bearing', sa.Integer(), nullable=True),
    sa.Column('driving_direction', sa.String(), nullable=True),
    sa.Column('fraction', sa.Numeric(), nullable=True),
    sa.Column('road_name', sa.String(), nullable=True),
    sa.Column('road_section_id', sa.BigInteger(), nullable=True),
    sa.Column('nwb_version', sa.String(), nullable=True),
    sa.Column('county_code', sa.String(), nullable=True),
    sa.Column('county_name', sa.String(), nullable=True),
    sa.Column('town_name', sa.String(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('text_signs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.Column('placed_on', sa.Date(), nullable=True),
    sa.Column('removed_on', sa.Date(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_traffic_sign_geom', 'traffic_sign', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('travel_time',
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Numeric(), nullable=True),
    sa.Column('ref_duration_s', sa.Numeric(), nullable=True),
    sa.Column('accuracy', sa.Numeric(), nullable=True),
    sa.Column('n_inputs', sa.Integer(), nullable=True),
    sa.Column('travel_time_type', sa.String(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('segment_id', 'index')
    )
    op.create_table('truck_parking',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_truck_parking_geom', 'truck_parking', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('vild_area',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vild_area_geom', 'vild_area', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('vild_line',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vild_line_geom', 'vild_line', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('vild_point',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vild_point_geom', 'vild_point', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('charge_availability',
    sa.Column('cp_id', sa.String(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('available', sa.Integer(), nullable=True),
    sa.Column('power_max', sa.Numeric(), nullable=True),
    sa.Column('power_type', sa.String(), nullable=True),
    sa.Column('connector_type', sa.String(), nullable=True),
    sa.Column('connector_format', sa.String(), nullable=True),
    sa.Column('tariff_ids', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cp_id'], ['charge_point.id'], ),
    sa.PrimaryKeyConstraint('cp_id', 'idx')
    )
    op.create_table('measurement_characteristic',
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.Column('period_s', sa.Integer(), nullable=True),
    sa.Column('value_type', sa.String(), nullable=True),
    sa.Column('veh_length_min', sa.Numeric(), nullable=True),
    sa.Column('veh_length_max', sa.Numeric(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['measurement_site.id'], ),
    sa.PrimaryKeyConstraint('site_id', 'index')
    )
    op.create_table('msi_state',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('ts_state', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aspect_type', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('flashing', sa.Boolean(), nullable=True),
    sa.Column('red_ring', sa.Boolean(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uuid'], ['msi_sign.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('traffic_measurement',
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value_type', sa.String(), nullable=True),
    sa.Column('flow_veh_h', sa.Numeric(), nullable=True),
    sa.Column('speed_kmh', sa.Numeric(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['measurement_site.id'], ),
    sa.PrimaryKeyConstraint('site_id', 'index')
    )
    op.create_table('truck_parking_status',
    sa.Column('parking_id', sa.String(), nullable=False),
    sa.Column('origin_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vacant', sa.Integer(), nullable=True),
    sa.Column('occupied', sa.Integer(), nullable=True),
    sa.Column('occupancy_pct', sa.Numeric(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parking_id'], ['truck_parking.id'], ),
    sa.PrimaryKeyConstraint('parking_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('truck_parking_status')
    op.drop_table('traffic_measurement')
    op.drop_table('msi_state')
    op.drop_table('measurement_characteristic')
    op.drop_table('charge_availability')
    op.drop_index('ix_vild_point_geom', table_name='vild_point', postgresql_using='gist')
    op.drop_table('vild_point')
    op.drop_index('ix_vild_line_geom', table_name='vild_line', postgresql_using='gist')
    op.drop_table('vild_line')
    op.drop_index('ix_vild_area_geom', table_name='vild_area', postgresql_using='gist')
    op.drop_table('vild_area')
    op.drop_index('ix_truck_parking_geom', table_name='truck_parking', postgresql_using='gist')
    op.drop_table('truck_parking')
    op.drop_table('travel_time')
    op.drop_index('ix_traffic_sign_geom', table_name='traffic_sign', postgresql_using='gist')
    op.drop_table('traffic_sign')
    op.drop_table('tariff')
    op.drop_index('ix_situation_geom', table_name='situation', postgresql_using='gist')
    op.drop_index('ix_situation_category', table_name='situation')
    op.drop_table('situation')
    op.drop_index('ix_msi_sign_geom', table_name='msi_sign', postgresql_using='gist')
    op.drop_table('msi_sign')
    op.drop_index('ix_meetlocatie_vak_geom', table_name='meetlocatie_vak', postgresql_using='gist')
    op.drop_table('meetlocatie_vak')
    op.drop_index('ix_meetlocatie_punt_geom', table_name='meetlocatie_punt', postgresql_using='gist')
    op.drop_table('meetlocatie_punt')
    op.drop_index('ix_measurement_site_geom', table_name='measurement_site', postgresql_using='gist')
    op.drop_table('measurement_site')
    op.drop_table('feed_run')
    op.drop_index('ix_emission_zone_geom', table_name='emission_zone', postgresql_using='gist')
    op.drop_table('emission_zone')
    op.drop_index('ix_drip_geom', table_name='drip', postgresql_using='gist')
    op.drop_table('drip')
    op.drop_index('ix_charge_point_geom', table_name='charge_point', postgresql_using='gist')
    op.drop_table('charge_point')
    # ### end Alembic commands ###
