"""add_raw_to_measurement_traveltime_msistate_parkingstatus

Revision ID: fb23bfc11eb5
Revises: d606f4f43b64
Create Date: 2026-05-29 16:16:37.243642

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb23bfc11eb5'
down_revision: Union[str, None] = 'd606f4f43b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('msi_state', sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('traffic_measurement', sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('travel_time', sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('truck_parking_status', sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('truck_parking_status', 'raw')
    op.drop_column('travel_time', 'raw')
    op.drop_column('traffic_measurement', 'raw')
    op.drop_column('msi_state', 'raw')
    # ### end Alembic commands ###
